require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/constants.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/tools.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/cell.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_reader.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/dir_cell_tree_factory.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/fifo.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_cell_utilities.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_contents_cell.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_parser.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_scope_cell.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/query_tool.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/directory_tree_builder.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/swim_lane.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/swim_lane_builder.rb"
# require ""
# require ""
# require ""
# require "pry"
require "byebug"
# require "./lib/tasks/lib/cpp_class_parser.rb"